In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.io
import seaborn as sns
import os
import h5py

In [43]:
group = "100_400"
data_dir = f"../data/{group}"
train_dir = os.path.join(data_dir, "train")
test_dir = os.path.join(data_dir, "test")
file_train = sorted([f for f in os.listdir(train_dir)])
file_test = sorted([f for f in os.listdir(test_dir)])
print(file_train)
print("\n")
print(file_test)

['P_train_ds_100_400_1.mat', 'P_train_ds_100_400_2.mat', 'P_train_ds_100_400_3.mat', 'P_train_ds_100_400_4.mat', 'P_train_ds_100_400_5.mat', 'T_train_ds_100_400_1.mat', 'T_train_ds_100_400_2.mat', 'T_train_ds_100_400_3.mat', 'T_train_ds_100_400_4.mat', 'T_train_ds_100_400_5.mat']


['100_400_1_test_label.csv', '100_400_2_test_label.csv', '100_400_3_test_label.csv', '100_400_4_test_label.csv', '100_400_5_test_label.csv', 'P_test_100_400_1.mat', 'P_test_100_400_2.mat', 'P_test_100_400_3.mat', 'P_test_100_400_4.mat', 'P_test_100_400_5.mat', 'label_100_400_1.mat']


In [45]:
train_set = h5py.File(os.path.join(test_dir, 'label_100_400_1.mat'))
dataset = train_set[list(train_set.keys())[0]]
print("Shape:", dataset.shape)
print("Total elements:", dataset.size)
print(train_set.keys())
train_set = train_set['T_test'][:]
print(train_set.shape)
train_set = train_set.transpose()
print(train_set.shape)

Shape: (1, 20000)
Total elements: 20000
<KeysViewHDF5 ['T_test']>
(1, 20000)
(20000, 1)


In [52]:
np.unique(train_set, return_counts=True)

(array([0., 1.]), array([ 9579, 10421]))

In [54]:
temp = pd.read_csv(os.path.join(test_dir, '100_400_1_test_label.csv'))
unique_values_counts = temp.apply(pd.Series.value_counts)
print(unique_values_counts)

       0
0       
1  10421
0   9578


In [56]:
temp.to_numpy().transpose()

array([[0, 0, 0, ..., 1, 1, 1]])

In [42]:
test_set = h5py.File(os.path.join(test_dir, 'label_100_400_1.mat'))
print(test_set.keys())
test_set = test_set['T_test'][:]
print(test_set.shape)
test_set = test_set.transpose()
print(test_set.shape)
print(test_set[:10])

<KeysViewHDF5 ['T_test']>
(1, 20000)
(20000, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [11]:
dir = "/media/sonvq9699/Study/master/dee_phage_data/dee_phage_data/dee_phage_data/all_data_to_train_model/all_data_to_train_model/100_400"
file_names = [f for f in os.listdir(dir)]
file_names

['100_400_all_train_model.h5',
 'P_train_ds.mat',
 'temp_100_400.fna',
 'T_train_ds.mat',
 'viru_100_400.fna']

In [32]:
from Bio import SeqIO

# Đọc file .fna
fasta_sequences = SeqIO.parse(os.path.join("../data/1/100_400", "viru_100_400.fna"), 'fasta')

count = 0
# Duyệt qua từng sequence
for sequence in fasta_sequences:
    count += 1
print(count)

40000


In [22]:

dir = "/media/sonvq9699/Study/master/dee_phage_data/dee_phage_data/dee_phage_data/training/training/MetaSim_simulating"
f = [f for f in os.listdir(dir)]
f

['800_1200_2_test.fna',
 'train_temp_400_800_3.fna',
 '100_400_1_test.fna',
 '100_400_2_test.fna',
 '100_400_3_test.fna',
 '100_400_4_test.fna',
 '100_400_5_test.fna',
 '1200_1800_1_test.fna',
 '1200_1800_2_test.fna',
 '1200_1800_3_test.fna',
 '1200_1800_4_test.fna',
 '1200_1800_5_test.fna',
 '400_800_1_test.fna',
 '400_800_2_test.fna',
 '400_800_3_test.fna',
 '400_800_4_test.fna',
 '400_800_5_test.fna',
 '800_1200_1_test.fna',
 '800_1200_3_test.fna',
 '800_1200_4_test.fna',
 '800_1200_5_test.fna',
 'train_temp_100_400_1.fna',
 'train_temp_100_400_2.fna',
 'train_temp_100_400_3.fna',
 'train_temp_100_400_4.fna',
 'train_temp_100_400_5.fna',
 'train_temp_1200_1800_1.fna',
 'train_temp_1200_1800_2.fna',
 'train_temp_1200_1800_3.fna',
 'train_temp_1200_1800_4.fna',
 'train_temp_1200_1800_5.fna',
 'train_temp_400_800_1.fna',
 'train_temp_400_800_2.fna',
 'train_temp_400_800_4.fna',
 'train_temp_400_800_5.fna',
 'train_temp_800_1200_1.fna',
 'train_temp_800_1200_2.fna',
 'train_temp_800_120

In [24]:
from Bio import SeqIO

# Đọc file .fna
fasta_sequences = SeqIO.parse(os.path.join(dir, "800_1200_5_test.fna"), 'fasta')

count = 0
# Duyệt qua từng sequence
for sequence in fasta_sequences:
    count += 1

    if count%10000==0:
        print("count: {}".format(count))
        # sequence.id - ID của trình tự
        # sequence.seq - chuỗi trình tự
        # sequence.description - mô tả đầy đủ
        print(f"ID: {sequence.id}")
        print(f"Sequence: {sequence.seq}")
        print(f"Description: {sequence.description}")

count: 10000
ID: r10000.1
Sequence: AAGCCGCTCGCGTGGAACGCAGCGCACGAACAGTTCTTCGCCGCCCGCGGCCGGCGCCAGCGCGTCTTTTGCTCGTCGCTTGCGGACGTGTTCGACAACGCGGTCTATCCGATGTGGCGAGTCGATCTCTTCGATTTGATCAGCAACACGCCAAATCTCGACTGGCTGCTACTGACGAAGCGAATCGGAAACGCGCGGGATATGATTTCCAGCGTCCTCGGCAGCATCATGCGCGATGAGCGTGAGTGGCCGTGGCCGCATGTCTGGCTCGGCGCGACGATCGTGAATCAGGCCGAGGCCGACCGCGACATTCCGAAGCTGCTCGCAGTGCCCGCTCGCGTGCGCTTCCTGTCGATGGAGCCTTTGCTCGGGCCGGTTGACCTTCGCTTCCACATCTACAGCGAGCCCACCGGCAATTTTCGTACGCACGGCGGCAAGCGCCAGCTCGAACTACGCCGGCCAGCCGACGGCGGCCTACATTGGGTGATCGCCGGCGGCGAAAGCGGCCACGGCGCCCGCCCGATGCATCCCGACTGGGCTCGCTCGCTGCGCGACCAGTGCGCAGCCGCCGGCGTGCCGTTCCTATTCAAGCAATGGGGCGAGTGGGCACCGCGAACAACTGACGAACAGAAGCTCCTTCCAGTCCCTTGCAGTCGCACCACTTCGTGGCCAGACGGGACTGTTGGATGTGGCGACTACCAGTCGAACGGTGACTACGGGAAGTGTCTTTTCCGCGTCGGCAAGAAAGCCACCGGCCGCATGCTTGACGGCCGCAGGCACGACGAATTCCCCGAGGTGACGCGATGAGCGGAAATTCGCAGTTCCCTAAAGCGGCACTAACTCCGGAGCTCAGCAAGCCTTGTATCGATAAGTGCGGCGGTATTCGAAAAGGAGTTCGAGAGAAACTTTCGCGCCTCGTCGCCCGGGGGAAATTCTGGAGCCGTCGTCAGATGAGCAATCATAA

In [28]:

import scipy
def load_mat(file_path):
    try:
        return scipy.io.loadmat(file_path)
    except NotImplementedError:
        return h5py.File(file_path, 'r')

In [41]:
data = load_mat(os.path.join("/media/sonvq9699/Study/master/dee_phage_data/dee_phage_data/dee_phage_data/training/training/five_fold_validation_prediction_label", "label_100_400_1.mat"))
data = data['T_test'][:].transpose()

In [30]:
data.keys()

<KeysViewHDF5 ['T_test']>

In [42]:
data[:10]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [36]:
type(data)

numpy.ndarray

In [39]:
unique_values, counts = np.unique(data, return_counts=True)
unique_values, counts

(array([0., 1.]), array([ 9579, 10421]))